use crate::ir::{DeviceTree, PropValue};

pub fn generate_rust(dt: &DeviceTree) -> String {
    let mut out = String::new();
    emit_header(&mut out);
    emit_prop_value_type(&mut out);
    emit_topology_type(&mut out);
    emit_peripheral_type(&mut out);
    emit_nodes(&mut out, dt);
    emit_peripherals(&mut out, dt);
    emit_query_api(&mut out, dt);
    emit_aliases_module(&mut out, dt);
    emit_memory_module(&mut out, dt);
    emit_chosen_module(&mut out, dt);
    out
}

// ------------------------------------------------------------------------------------------------
// File header
// ------------------------------------------------------------------------------------------------

fn emit_header(out: &mut String) {
    out.push_str(
        r#"// ------------------------------------------------------------------------------------------------
// AUTOGENERATED BY dtgen - DO NOT EDIT FILE
// ------------------------------------------------------------------------------------------------

"#,
    );
}

// ------------------------------------------------------------------------------------------------
// Type defitions
// ------------------------------------------------------------------------------------------------

fn emit_prop_value_type(out: &mut String) {
    out.push_str(
        r#"#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum PropValue {
    Empty,
    U32(u32),
    U32Array(&'static [u32]),
    Str(&'static str),
    StringList(&'static [&'static str]),
    Bytes(&'static [u8]),
}

"#,
    );
}

fn emit_topology_type(out: &mut String) {
    out.push_str(
        r#"#[allow(dead_code)]
#[derive(Debug, Clone, Copy)]
pub struct TreeNode {
    pub name:     &'static str,
    pub phandle:  Option<u32>,
    pub parent:   Option<usize>,
    pub children: &'static [usize],
}

impl TreeNode {
    // returns the parent TreeNode, if any.
    pub fn parent_node(&self) -> Option<&'static TreeNode> {
        self.parent.map(|idx| &NODES[idx])
    }

    // iterate children as (node_index, &TreeNode).
    pub fn iter_children(&self) -> impl Iterator<Item = (usize, &'static TreeNode)> {
        self.children.iter().map(|&idx| (idx, &NODES[idx]))
    }
}

"#,
    );
}

fn emit_peripheral_type(out: &mut String) {
    out.push_str(
        r#"#[allow(dead_code)]
#[derive(Debug, Clone, Copy)]
pub struct Peripheral {
    pub node:       usize,
    pub compatible: &'static [&'static str],
    pub reg:        Option<(usize, usize)>,
    pub interrupts: &'static [u32],
    pub phandle:    Option<u32>,
    pub props:      &'static [(&'static str, PropValue)],
}

impl Peripheral {
    // returns true if any compatible string exactly matches `c`
    pub fn is_compatible(&self, c: &str) -> bool {
        self.compatible.iter().any(|&s| s == c)
    }

    // returns true if any compatible string contains `fragment` as a substring
    pub fn compatible_contains(&self, fragment: &str) -> bool {
        self.compatible.iter().any(|&s| s.contains(fragment))
    }

    // look up a prop by key, returning the raw PropValue
    pub fn prop(&self, key: &str) -> Option<PropValue> {
        self.props.iter().find(|(k, _)| *k == key).map(|(_, v)| *v)
    }

    // get a u32 prop
    pub fn prop_u32(&self, key: &str) -> Option<u32> {
        match self.prop(key) {
            Some(PropValue::U32(v)) => Some(v),
            _ => None,
        }
    }

    // get a str prop
    pub fn prop_str(&self, key: &str) -> Option<&'static str> {
        match self.prop(key) {
            Some(PropValue::Str(s)) => Some(s),
            _ => None,
        }
    }

    // get a u32 array prop
    pub fn prop_u32_array(&self, key: &str) -> Option<&'static [u32]> {
        match self.prop(key) {
            Some(PropValue::U32Array(arr)) => Some(arr),
            _ => None,
        }
    }

    // returns the base address from reg, if present
    pub fn reg_base(&self) -> Option<usize> {
        self.reg.map(|(base, _)| base)
    }

    // returns the size from reg, if present
    pub fn reg_size(&self) -> Option<usize> {
        self.reg.map(|(_, size)| size)
    }

    // resolve a phandle value (e.g. from a clocks prop) to another Peripheral
    pub fn resolve_phandle(&self, ph: u32) -> Option<&'static Peripheral> {
        peripheral_by_phandle(ph)
    }

    // returns the TreeNode for this peripheral.
    pub fn tree_node(&self) -> &'static TreeNode {
        &NODES[self.node]
    }

    // returns true if status prop is absent or set to "okay"
    pub fn is_enabled(&self) -> bool {
        match self.prop_str("status") {
            Some(s) => s == "okay",
            None => true,
        }
    }
}

"#,
    );
}

// ------------------------------------------------------------------------------------------------
// Nodes
// ------------------------------------------------------------------------------------------------

fn emit_nodes(out: &mut String, dt: &DeviceTree) {
    out.push_str("pub const NODES: &[TreeNode] = &[\n");
    for (i, node) in dt.nodes.iter().enumerate() {
        let phandle = opt_u32(node.phandle);
        let parent = opt_usize(node.parent);
        let children = if node.children.is_empty() {
            "&[]".to_string()
        } else {
            let inner: Vec<String> = node.children.iter().map(|c| c.to_string()).collect();
            format!("&[{}]", inner.join(", "))
        };
        out.push_str(&format!(
            "    // {i}\n    TreeNode {{ name: {:?}, phandle: {phandle}, parent: {parent}, children: {children} }},\n",
            node.name,
        ));
    }
    out.push_str("];\n\n");
}

// ------------------------------------------------------------------------------------------------
// Peripherals
// ------------------------------------------------------------------------------------------------

fn emit_peripherals(out: &mut String, dt: &DeviceTree) {
    let mut indices: Vec<usize> = Vec::new();
    dt.walk(|idx, node| {
        if !node.compatible.is_empty() {
            indices.push(idx);
        }
    });

    // emit per-node prop sub-consts (only for types that cannot be inlined)
    for (i, &idx) in indices.iter().enumerate() {
        let node = &dt.nodes[idx];

        let mut sorted_extra: Vec<(&String, &PropValue)> = node.extra.iter().collect();
        sorted_extra.sort_by_key(|(k, _)| k.as_str());

        for (j, (_, val)) in sorted_extra.iter().enumerate() {
            match val {
                PropValue::U32Array(arr) => {
                    let vals: Vec<String> = arr.iter().map(|v| v.to_string()).collect();
                    out.push_str(&format!(
                        "const PERIPH_{i}_PROP_{j}: &[u32] = &[{}];\n",
                        vals.join(", ")
                    ));
                }
                PropValue::StringList(list) => {
                    let strs: Vec<String> = list.iter().map(|s| format!("{:?}", s)).collect();
                    out.push_str(&format!(
                        "const PERIPH_{i}_PROP_{j}_STRS: &[&str] = &[{}];\n",
                        strs.join(", ")
                    ));
                }
                PropValue::Bytes(b) => {
                    let bytes: Vec<String> = b.iter().map(|v| format!("{:#04x}", v)).collect();
                    out.push_str(&format!(
                        "const PERIPH_{i}_PROP_{j}_BYTES: &[u8] = &[{}];\n",
                        bytes.join(", ")
                    ));
                }
                _ => {}
            }
        }

        // props array
        let mut prop_entries: Vec<String> = Vec::new();
        for (j, (key, val)) in sorted_extra.iter().enumerate() {
            let pv = match val {
                PropValue::Empty => "PropValue::Empty".to_string(),
                PropValue::U32(v) => format!("PropValue::U32({v})"),
                PropValue::U32Array(_) => format!("PropValue::U32Array(PERIPH_{i}_PROP_{j})"),
                PropValue::Str(s) => format!("PropValue::Str({:?})", s),
                PropValue::StringList(_) => {
                    format!("PropValue::StringList(PERIPH_{i}_PROP_{j}_STRS)")
                }
                PropValue::Bytes(_) => format!("PropValue::Bytes(PERIPH_{i}_PROP_{j}_BYTES)"),
            };
            prop_entries.push(format!("    ({:?}, {})", key, pv));
        }

        out.push_str(&format!(
            "const PERIPH_{i}_PROPS: &[(&str, PropValue)] = &[\n{}\n];\n",
            prop_entries.join(",\n")
        ));
    }

    out.push('\n');
    out.push_str("pub const PERIPHERALS: &[Peripheral] = &[\n");

    for (i, &idx) in indices.iter().enumerate() {
        let node = &dt.nodes[idx];

        let compats: Vec<String> = node.compatible.iter().map(|c| format!("{:?}", c)).collect();
        let compat_inline = format!("&[{}]", compats.join(", "));

        let reg = match node.reg {
            Some((base, size)) => format!("Some(({:#010x}, {:#x}))", base, size),
            None => "None".to_string(),
        };

        let irqs = if node.interrupts.is_empty() {
            "&[]".to_string()
        } else {
            let vals: Vec<String> = node.interrupts.iter().map(|v| v.to_string()).collect();
            format!("&[{}]", vals.join(", "))
        };

        let phandle = opt_u32(node.phandle);

        out.push_str(&format!(
            "    // {i} - node {idx}: {:?}\n    Peripheral {{ node: {idx}, compatible: {compat_inline}, reg: {reg}, interrupts: {irqs}, phandle: {phandle}, props: PERIPH_{i}_PROPS }},\n",
            node.name,
        ));
    }

    out.push_str("];\n\n");
}

// ------------------------------------------------------------------------------------------------
// Query API
// ------------------------------------------------------------------------------------------------

fn emit_query_api(out: &mut String, dt: &DeviceTree) {
    out.push_str(
        r#"// find the first enabled peripheral for which any compatible string equals `c`.
pub fn peripheral_by_compatible(c: &str) -> Option<&'static Peripheral> {
    PERIPHERALS.iter().find(|p| p.is_compatible(c) && p.is_enabled())
}

// iterate all enabled peripherals for which any compatible string equals `c`
pub fn peripherals_by_compatible(c: &str) -> impl Iterator<Item = &'static Peripheral> {
    PERIPHERALS.iter().filter(move |p| p.is_compatible(c) && p.is_enabled())
}

// find a peripheral by its phandle value
// ignores enabled status - phandle targets like clock providers may have no status prop
// phandle values are unique
pub fn peripheral_by_phandle(ph: u32) -> Option<&'static Peripheral> {
    PERIPHERALS.iter().find(|p| p.phandle == Some(ph))
}

// find a peripheral by its NODES index
// NODES indices are unique
pub fn peripheral_by_node(idx: usize) -> Option<&'static Peripheral> {
    PERIPHERALS.iter().find(|p| p.node == idx)
}

// iterate all peripherals whose node name matches, with or without unit address
// e.g. "channel" matches "channel@0", "channel@1", etc. across all parents
// node names are only unique among siblings - use peripheral_by_name_under or
// peripheral_by_path when you need an unambiguous match
pub fn peripherals_by_name(name: &str) -> impl Iterator<Item = &'static Peripheral> {
    PERIPHERALS.iter().filter(move |p| {
        let n = NODES[p.node].name;
        n == name || n.split('@').next() == Some(name)
    })
}

// find a peripheral by name scoped to a specific parent node index
// safe form of name lookup since node names are only unique among siblings
// e.g. peripheral_by_name_under("channel", adc1.node) returns adc1's channel@0
pub fn peripheral_by_name_under(name: &str, parent_node: usize) -> Option<&'static Peripheral> {
    PERIPHERALS.iter().find(|p| {
        let n = NODES[p.node].name;
        let name_matches = n == name || n.split('@').next() == Some(name);
        let parent_matches = NODES[p.node].parent == Some(parent_node);

        name_matches && parent_matches
    })
}

// find a peripheral by its full path from root, with or without unit addresses
// e.g. "soc/i2c@40005400/lsm6dsl@6a" or "soc/i2c/lsm6dsl"
// at each level the first sibling whose name matches is taken
pub fn peripheral_by_path(path: &str) -> Option<&'static Peripheral> {
    let segments: Vec<&str> = path.trim_start_matches('/').split('/').collect();
    let mut current = 0usize;
    for segment in &segments {
        let child = NODES[current].children.iter().find(|&&idx| {
            let n = NODES[idx].name;
            n == *segment || n.split('@').next() == Some(*segment)
        })?;

        current = *child;
    }

    peripheral_by_node(current)
}
"#,
    );
}

fn resolve_path(dt: &DeviceTree, path: &str) -> Option<usize> {
    if path == "/" {
        return Some(dt.root);
    }

    let mut current_idx = dt.root;

    // split "/soc/serial@40013800" into ["soc", "serial@40013800"]
    let segments = path.split('/').filter(|s| !s.is_empty());
    for segment in segments {
        let current_node = &dt.nodes[current_idx];

        // look through children of the current node for a matching name
        let found_child = current_node
            .children
            .iter()
            .find(|&&child_idx| dt.nodes[child_idx].name == segment);

        if let Some(&next_idx) = found_child {
            current_idx = next_idx;
        } else {
            return None; // Path broken
        }
    }
    Some(current_idx)
}

// ------------------------------------------------------------------------------------------------
// Alias module
// ------------------------------------------------------------------------------------------------

fn emit_aliases_module(out: &mut String, dt: &DeviceTree) {
    let mut pairs: Vec<(String, usize)> = dt
        .by_name
        .get("aliases")
        .and_then(|indices| indices.first()) // there is usually only one /aliases node
        .map(|&idx| {
            dt.nodes[idx]
                .extra
                .iter()
                .filter_map(|(k, val)| {
                    if let crate::ir::PropValue::Str(path) = val {
                        // resolve the full path to a unique index
                        resolve_path(dt, path).map(|target_idx| (k.clone(), target_idx))
                    } else {
                        None
                    }
                })
                .collect()
        })
        .unwrap_or_default();

    // sort by alias name (e.g., serial0, serial1) for deterministic output
    pairs.sort_by(|a, b| a.0.cmp(&b.0));

    out.push('\n');

    out.push_str(&format!("// {}\n", "-".repeat(96)));
    out.push_str("// Aliases\n");
    out.push_str(&format!("// {}\n\n", "-".repeat(96)));

    out.push_str("pub mod aliases {\n");
    out.push_str("    use super::*;\n\n");

    // emit the slice of tuples: (alias_name, node_index)
    out.push_str("    pub const ALIASES: &[(&str, usize)] = &[\n");
    for (name, idx) in &pairs {
        out.push_str(&format!("        ({:?}, {}),\n", name, idx));
    }

    out.push_str("    ];\n\n");
    out.push_str(
        r#"    // resolve an alias name to its Peripheral
    pub fn resolve(alias: &str) -> Option<&'static Peripheral> {
        ALIASES
            .iter()
            .find(|(k, _)| *k == alias)
            .and_then(|(_, idx)| peripheral_by_node(*idx))
    }
"#,
    );

    out.push_str("}\n");
}

// ------------------------------------------------------------------------------------------------
// Memory module
// ------------------------------------------------------------------------------------------------

fn emit_memory_module(out: &mut String, dt: &DeviceTree) {
    // the device tree speciciation states that for a memory node this field must exist and be set
    // to "memory"
    let mut regions: Vec<(&str, u64, u64)> = dt
        .nodes
        .iter()
        .filter(|n| {
            n.extra
                .get("device_type")
                .map(|v| matches!(v, crate::ir::PropValue::Str(s) if s == "memory"))
                .unwrap_or(false)
        })
        .filter_map(|n| {
            let (base, size) = n.reg?;
            Some((n.name.as_str(), base, size))
        })
        .collect();

    // sort by base address for deterministic, predictable output
    regions.sort_by_key(|&(_, base, _)| base);

    out.push('\n');

    out.push_str(&format!("// {}\n", "-".repeat(96)));
    out.push_str("// Memory regions\n");
    out.push_str(&format!("// {}\n\n", "-".repeat(96)));

    out.push_str("pub mod memory {\n");
    out.push_str("    use super::*;\n\n");
    out.push_str("    pub const REGIONS: &[(&str, usize, usize)] = &[\n");

    for (name, base, size) in &regions {
        out.push_str(&format!(
            "        ({:?}, {:#010x}, {:#010x}),\n",
            name, base, size
        ));
    }

    out.push_str("    ];\n\n");
    out.push_str(
        r#"    // find a memory region by node name
    pub fn region_by_name(name: &str) -> Option<(usize, usize)> {
        REGIONS
            .iter()
            .find(|(n, _, _)| *n == name)
            .map(|(_, base, size)| (*base, *size))
    }

    // total memory in bytes across all declared regions
    pub fn total_bytes() -> usize {
        REGIONS.iter().map(|(_, _, size)| size).sum()
    }
"#,
    );
    out.push_str("}\n");
}

fn emit_chosen_module(out: &mut String, dt: &DeviceTree) {
    let chosen = dt
        .by_name
        .get("chosen")
        .and_then(|indices| indices.first())
        .map(|&idx| &dt.nodes[idx]);

    let mut periph_indices: Vec<usize> = Vec::new();
    dt.walk(|idx, node| {
        if !node.compatible.is_empty() {
            periph_indices.push(idx);
        }
    });

    // --------------------------------------------------------------------------------------------
    // Standard properties
    // --------------------------------------------------------------------------------------------

    let stdout_periph_idx: Option<usize> = chosen.and_then(|n| {
        if let Some(crate::ir::PropValue::Str(raw)) = n.extra.get("stdout-path") {
            let path = raw.split(':').next().unwrap_or(raw);

            let node_idx = if path.contains('/') {
                resolve_path(dt, path)
            } else {
                dt.by_name
                    .get("aliases")
                    .and_then(|ids| ids.first())
                    .and_then(|&aidx| {
                        if let Some(crate::ir::PropValue::Str(resolved)) =
                            dt.nodes[aidx].extra.get(path)
                        {
                            resolve_path(dt, resolved)
                        } else {
                            None
                        }
                    })
            }?;

            periph_indices.iter().position(|&idx| idx == node_idx)
        } else {
            None
        }
    });

    let bootargs: Option<&str> = chosen.and_then(|n| {
        if let Some(crate::ir::PropValue::Str(s)) = n.extra.get("bootargs") {
            Some(s.as_str())
        } else {
            None
        }
    });

    // --------------------------------------------------------------------------------------------
    // Extra properties
    // --------------------------------------------------------------------------------------------

    const KNOWN: &[&str] = &["stdout-path", "bootargs"];
    let extras: Vec<(&str, &crate::ir::PropValue)> = chosen
        .map(|n| {
            let mut v: Vec<_> = n
                .extra
                .iter()
                .filter(|(k, _)| !KNOWN.contains(&k.as_str()))
                .map(|(k, v)| (k.as_str(), v))
                .collect();
            v.sort_by_key(|(k, _)| *k);
            v
        })
        .unwrap_or_default();

    // --------------------------------------------------------------------------------------------
    // Emit
    // --------------------------------------------------------------------------------------------

    out.push('\n');
    out.push_str(&format!("// {}\n", "-".repeat(96)));
    out.push_str("// Chosen\n");
    out.push_str(&format!("// {}\n\n", "-".repeat(96)));

    // U32Array and Bytes backing statics must live outside the mod block
    for (i, (_, val)) in extras.iter().enumerate() {
        match val {
            crate::ir::PropValue::U32Array(arr) => {
                out.push_str(&format!("static CHOSEN_EXTRA_{i}: &[u32] = &{arr:?};\n"));
            }
            crate::ir::PropValue::Bytes(arr) => {
                out.push_str(&format!("static CHOSEN_EXTRA_{i}: &[u8] = &{arr:?};\n"));
            }
            _ => {}
        }
    }

    out.push_str("pub mod chosen {\n");
    out.push_str("    use super::*;\n\n");

    match stdout_periph_idx {
        Some(idx) => out.push_str(&format!(
            "    // index into PERIPHERALS of the stdout peripheral, resolved from stdout-path\n    pub const STDOUT: Option<usize> = Some({idx});\n"
        )),
        None => out.push_str("    pub const STDOUT: Option<usize> = None;\n"),
    }

    match bootargs {
        Some(s) => out.push_str(&format!(
            "    pub const BOOTARGS: Option<&str> = Some({:?});\n",
            s
        )),
        None => out.push_str("    pub const BOOTARGS: Option<&str> = None;\n"),
    }

    out.push('\n');
    out.push_str("    // non-standard properties of the chosen node\n");
    out.push_str("    pub const EXTRAS: &[(&str, PropValue)] = &[\n");
    for (i, (key, val)) in extras.iter().enumerate() {
        let expr = match val {
            crate::ir::PropValue::Empty => "PropValue::Empty".to_string(),
            crate::ir::PropValue::U32(v) => format!("PropValue::U32({v:#010x})"),
            crate::ir::PropValue::U32Array(_) => {
                format!("PropValue::U32Array(CHOSEN_EXTRA_{i}.to_vec())")
            }
            crate::ir::PropValue::Str(s) => format!("PropValue::Str({s:?})"),
            crate::ir::PropValue::StringList(sl) => format!("PropValue::StringList(vec!{sl:?})"),
            crate::ir::PropValue::Bytes(_) => {
                format!("PropValue::Bytes(CHOSEN_EXTRA_{i}.to_vec())")
            }
        };
        out.push_str(&format!("        ({key:?}, {expr}),\n"));
    }

    out.push_str("    ];\n\n");
    out.push_str(
        r#"    // resolve stdout to its Peripheral directly via PERIPHERALS index
    pub fn stdout() -> Option<&'static Peripheral> {
        STDOUT.map(|idx| &PERIPHERALS[idx])
    }
}

"#,
    );
}

// ------------------------------------------------------------------------------------------------
// Formatting helpers
// ------------------------------------------------------------------------------------------------

fn opt_u32(v: Option<u32>) -> String {
    match v {
        Some(n) => format!("Some({n})"),
        None => "None".to_string(),
    }
}

fn opt_usize(v: Option<usize>) -> String {
    match v {
        Some(n) => format!("Some({n})"),
        None => "None".to_string(),
    }
}
