use crate::ir::{DeviceTree, PropValue};
use proc_macro2::TokenStream;
use quote::quote;

pub fn generate_rust(dt: &DeviceTree) -> String {
    let segments: &[TokenStream] = &[
        emit_prop_value_type(),
        emit_topology_type(),
        emit_peripheral_type(),
        emit_nodes(dt),
        emit_peripherals(dt),
        emit_query_api(),
        i2c::emit_registry(dt),
        i2c::emit_query_api(),
        spi::emit_registry(dt),
        spi::emit_query_api(),
        emit_aliases_module(dt),
        emit_memory_module(dt),
        emit_chosen_module(dt),
    ];

    let combined = segments.iter().cloned().collect::<TokenStream>();
    let wrapped = quote! {
        pub mod device_tree {
            #combined
        }
    };

    let file: syn::File = syn::parse2(wrapped).unwrap();
    let mut out = emit_header();
    out.push_str(&prettyplease::unparse(&file));
    out
}

// ------------------------------------------------------------------------------------------------
// File header
// ------------------------------------------------------------------------------------------------

fn emit_header() -> String {
    r#"// ------------------------------------------------------------------------------------------------
// AUTOGENERATED BY dtgen - DO NOT EDIT FILE
// ------------------------------------------------------------------------------------------------

"#
    .to_string()
}

// ------------------------------------------------------------------------------------------------
// Type defitions
// ------------------------------------------------------------------------------------------------

fn emit_prop_value_type() -> TokenStream {
    quote! {
        #[allow(dead_code)]
        #[derive(Debug, Clone, Copy, PartialEq)]
        pub enum PropValue {
            Empty,
            U32(u32),
            U32Array(&'static [u32]),
            Str(&'static str),
            StringList(&'static [&'static str]),
            Bytes(&'static [u8]),
        }
    }
}

fn emit_topology_type() -> TokenStream {
    quote! {
        #[allow(dead_code)]
        #[derive(Debug, Clone, Copy)]
        pub struct TreeNode {
            pub name:     &'static str,
            pub phandle:  Option<u32>,
            pub parent:   Option<usize>,
            pub children: &'static [usize],
        }

        impl TreeNode {
            #[doc = "returns the parent TreeNode, if any"]
            pub fn parent_node(&self) -> Option<&'static TreeNode> {
                self.parent.map(|idx| &NODES[idx])
            }

            #[doc = "iterate children as (node_index, &TreeNode)"]
            pub fn iter_children(&self) -> impl Iterator<Item = (usize, &'static TreeNode)> {
                self.children.iter().map(|&idx| (idx, &NODES[idx]))
            }
        }
    }
}

fn emit_peripheral_type() -> TokenStream {
    quote! {
        #[allow(dead_code)]
        #[derive(Debug, Clone, Copy)]
        pub struct Peripheral {
            pub node:       usize,
            pub compatible: &'static [&'static str],
            pub reg:        Option<(usize, usize)>,
            pub interrupts: &'static [u32],
            pub phandle:    Option<u32>,
            pub props:      &'static [(&'static str, PropValue)],
        }

        impl Peripheral {
            #[doc = "returns true if any compatible string exactly matches `c`"]
            pub fn is_compatible(&self, c: &str) -> bool {
                self.compatible.iter().any(|&s| s == c)
            }

            #[doc = "returns true if any compatible string contains `fragment` as a substring"]
            pub fn compatible_contains(&self, fragment: &str) -> bool {
                self.compatible.iter().any(|&s| s.contains(fragment))
            }

            #[doc = "look up a prop by key, returning the raw PropValue"]
            pub fn prop(&self, key: &str) -> Option<PropValue> {
                self.props.iter().find(|(k, _)| *k == key).map(|(_, v)| *v)
            }

            #[doc = "get a u32 prop"]
            pub fn prop_u32(&self, key: &str) -> Option<u32> {
                match self.prop(key) {
                    Some(PropValue::U32(v)) => Some(v),
                    _ => None,
                }
            }

            #[doc = "get a str prop"]
            pub fn prop_str(&self, key: &str) -> Option<&'static str> {
                match self.prop(key) {
                    Some(PropValue::Str(s)) => Some(s),
                    _ => None,
                }
            }

            #[doc = "get a u32 array prop"]
            pub fn prop_u32_array(&self, key: &str) -> Option<&'static [u32]> {
                match self.prop(key) {
                    Some(PropValue::U32Array(arr)) => Some(arr),
                    _ => None,
                }
            }

            #[doc = "returns the base address from reg, if present"]
            pub fn reg_base(&self) -> Option<usize> {
                self.reg.map(|(base, _)| base)
            }

            #[doc = "returns the size from reg, if present"]
            pub fn reg_size(&self) -> Option<usize> {
                self.reg.map(|(_, size)| size)
            }

            #[doc = "resolve a phandle value (e.g. from a clocks prop) to another Peripheral"]
            pub fn resolve_phandle(&self, ph: u32) -> Option<&'static Peripheral> {
                peripheral_by_phandle(ph)
            }

            #[doc = "returns the TreeNode for this peripheral"]
            pub fn tree_node(&self) -> &'static TreeNode {
                &NODES[self.node]
            }

            #[doc = "returns true if status prop is absent or set to \"okay\""]
            pub fn is_enabled(&self) -> bool {
                match self.prop_str("status") {
                    Some(s) => s == "okay",
                    None => true,
                }
            }
        }
    }
}

// ------------------------------------------------------------------------------------------------
// Nodes
// ------------------------------------------------------------------------------------------------

fn emit_nodes(dt: &DeviceTree) -> TokenStream {
    let entries = dt.nodes.iter().map(|node| {
        let name = node.name.as_str();
        let phandle = node
            .phandle
            .map_or(quote! { None }, |v| quote! { Some(#v) });
        let parent = node.parent.map_or(quote! { None }, |v| quote! { Some(#v) });
        let children = &node.children;

        quote! {
            TreeNode {
                name: #name,
                phandle: #phandle,
                parent: #parent,
                children: &[#(#children),*],
            },
        }
    });

    quote! {
        pub const NODES: &[TreeNode] = &[
            #(#entries)*
        ];
    }
}

// ------------------------------------------------------------------------------------------------
// Peripherals
// ------------------------------------------------------------------------------------------------

fn emit_peripherals(dt: &DeviceTree) -> TokenStream {
    let mut indices: Vec<usize> = Vec::new();
    dt.walk(|idx, node| {
        if !node.compatible.is_empty() {
            indices.push(idx);
        }
    });

    let mut backing_statics = TokenStream::new();
    let mut peripheral_entries = Vec::new();

    for (i, &idx) in indices.iter().enumerate() {
        let node = &dt.nodes[idx];
        let mut sorted_extra: Vec<(&String, &PropValue)> = node.extra.iter().collect();
        sorted_extra.sort_by_key(|(k, _)| k.as_str());

        // backing statics for non-inline prop types
        for (j, (_, val)) in sorted_extra.iter().enumerate() {
            match val {
                PropValue::U32Array(arr) => {
                    let ident = quote::format_ident!("PERIPH_{}_PROP_{}", i, j);
                    backing_statics.extend(quote! {
                        const #ident: &[u32] = &[#(#arr),*];
                    });
                }
                PropValue::StringList(list) => {
                    let ident = quote::format_ident!("PERIPH_{}_PROP_{}_STRS", i, j);
                    backing_statics.extend(quote! {
                        const #ident: &[&str] = &[#(#list),*];
                    });
                }
                PropValue::Bytes(b) => {
                    let ident = quote::format_ident!("PERIPH_{}_PROP_{}_BYTES", i, j);
                    backing_statics.extend(quote! {
                        const #ident: &[u8] = &[#(#b),*];
                    });
                }
                _ => {}
            }
        }

        // props array
        let props_ident = quote::format_ident!("PERIPH_{}_PROPS", i);
        let prop_entries = sorted_extra.iter().enumerate().map(|(j, (key, val))| {
            let val_tokens = match val {
                PropValue::Empty => quote! { PropValue::Empty },
                PropValue::U32(v) => quote! { PropValue::U32(#v) },
                PropValue::U32Array(_) => {
                    let ident = quote::format_ident!("PERIPH_{}_PROP_{}", i, j);
                    quote! { PropValue::U32Array(#ident) }
                }
                PropValue::Str(s) => quote! { PropValue::Str(#s) },
                PropValue::StringList(_) => {
                    let ident = quote::format_ident!("PERIPH_{}_PROP_{}_STRS", i, j);
                    quote! { PropValue::StringList(#ident) }
                }
                PropValue::Bytes(_) => {
                    let ident = quote::format_ident!("PERIPH_{}_PROP_{}_BYTES", i, j);
                    quote! { PropValue::Bytes(#ident) }
                }
            };

            quote! { (#key, #val_tokens), }
        });

        backing_statics.extend(quote! {
            const #props_ident: &[(&str, PropValue)] = &[
                #(#prop_entries)*
            ];
        });

        // peripheral entry
        let compat_strs = node.compatible.iter().map(|c| c.as_str());
        let reg_tokens = match node.reg {
            Some((base, size)) => {
                let base_lit =
                    syn::LitInt::new(&format!("{base:#010x}"), proc_macro2::Span::call_site());
                let size_lit =
                    syn::LitInt::new(&format!("{size:#x}"), proc_macro2::Span::call_site());

                quote! { Some((#base_lit, #size_lit)) }
            }
            None => quote! { None },
        };

        // automatic fallback to &[] on empty
        let irqs = &node.interrupts;
        let phandle_tokens = match node.phandle {
            Some(v) => quote! { Some(#v) },
            None => quote! { None },
        };

        peripheral_entries.push(quote! {
            Peripheral {
                node: #idx,
                compatible: &[#(#compat_strs),*],
                reg: #reg_tokens,
                interrupts: &[#(#irqs),*],
                phandle: #phandle_tokens,
                props: #props_ident,
            },
        });
    }

    quote! {
        #backing_statics

        pub const PERIPHERALS: &[Peripheral] = &[
            #(#peripheral_entries)*
        ];
    }
}

// ------------------------------------------------------------------------------------------------
// Query API
// ------------------------------------------------------------------------------------------------

fn emit_query_api() -> TokenStream {
    quote! {
        #[doc = "find the first enabled peripheral for which any compatible string equals `c`"]
        pub fn peripheral_by_compatible(c: &str) -> Option<&'static Peripheral> {
            PERIPHERALS.iter().find(|p| p.is_compatible(c) && p.is_enabled())
        }

        #[doc = "iterate all enabled peripherals for which any compatible string equals `c`"]
        pub fn peripherals_by_compatible(c: &str) -> impl Iterator<Item = &'static Peripheral> {
            PERIPHERALS.iter().filter(move |p| p.is_compatible(c) && p.is_enabled())
        }

        #[doc = "find a peripheral by its phandle value"]
        #[doc = "ignores enabled status - phandle targets like clock providers may have no status prop"]
        #[doc = "phandle values are unique"]
        pub fn peripheral_by_phandle(ph: u32) -> Option<&'static Peripheral> {
            PERIPHERALS.iter().find(|p| p.phandle == Some(ph))
        }

        #[doc = "find a peripheral by its NODES index"]
        #[doc = "NODES indices are unique"]
        pub fn peripheral_by_node(idx: usize) -> Option<&'static Peripheral> {
            PERIPHERALS.iter().find(|p| p.node == idx)
        }

        #[doc = "iterate all peripherals whose node name matches, with or without unit address"]
        #[doc = "e.g. `channel` matches `channel@0`, `channel@1`, etc. across all parents"]
        #[doc = "node names are only unique among siblings - use `peripheral_by_name_under` or"]
        #[doc = "`peripheral_by_path` when you need an unambiguous match"]
        pub fn peripherals_by_name(name: &str) -> impl Iterator<Item = &'static Peripheral> {
            PERIPHERALS.iter().filter(move |p| {
                let n = NODES[p.node].name;
                n == name || n.split('@').next() == Some(name)
            })
        }

        #[doc = "find a peripheral by name scoped to a specific parent node index"]
        #[doc = "safe form of name lookup since node names are only unique among siblings"]
        pub fn peripheral_by_name_under(
            name: &str,
            parent_node: usize,
        ) -> Option<&'static Peripheral> {
            PERIPHERALS.iter().find(|p| {
                let n = NODES[p.node].name;
                let name_matches = n == name || n.split('@').next() == Some(name);
                let parent_matches = NODES[p.node].parent == Some(parent_node);

                name_matches && parent_matches
            })
        }

        #[doc = "find a peripheral by its full path from root, with or without unit addresses"]
        #[doc = "e.g. `soc/i2c@40005400/lsm6dsl@6a` or `soc/i2c/lsm6dsl`"]
        #[doc = "at each level the first sibling whose name matches is taken"]
        pub fn peripheral_by_path(path: &str) -> Option<&'static Peripheral> {
            let mut current = 0usize;
            for segment in path.trim_start_matches('/').split('/') {
                let child = NODES[current].children.iter().find(|&&idx| {
                    let n = NODES[idx].name;
                    n == segment || n.split('@').next() == Some(segment)
                })?;

                current = *child;
            }

            peripheral_by_node(current)
        }
    }
}

// ------------------------------------------------------------------------------------------------
// Helpers
// ------------------------------------------------------------------------------------------------

macro_rules! match_compatible {
    ($compat:expr, {
        $($pat:literal => $body:expr),+ $(,)?
    }) => {{
        let compat = $compat;
        let mut matched = None;

        $(
            if matched.is_none() && compat.iter().any(|c| c == $pat) {
                matched = Some($body);
            }
        )+

        matched
    }};
}

/// Returns true if the "status" prop is absent or set to okay.
fn is_enabled(node: &crate::ir::Node) -> bool {
    match node.extra.get("status") {
        Some(PropValue::Str(s)) => s == "okay",
        _ => true,
    }
}

// Returns a vector of (gpio_controller(block) phandle, pin_number, active_low)
fn decode_gpio_pins<'a>(dt: &'a DeviceTree, gpios: &[u32]) -> Vec<(&'a crate::ir::Node, u8, u8)> {
    let mut pins = Vec::new();
    for chunk in gpios.chunks(3) {
        if chunk.len() < 3 {
            panic!("Invalid GPIO spec - expected groups of 3 u32 values (phandle, pin, flags)");
        }
        let phandle = chunk[0];
        let pin = chunk[1] as u8;
        let flags = chunk[2];
        let active_low = (flags & 1) != 0;

        let idx = dt
            .resolve_phandle_idx(phandle)
            .unwrap_or_else(|| panic!("Invalid phandle in GPIO spec: {phandle:#x}"));
        pins.push((&dt.nodes[idx], pin, active_low as u8));
    }
    pins
}

// ------------------------------------------------------------------------------------------------
// I2C registry
// ------------------------------------------------------------------------------------------------

mod i2c {
    use super::*;
    use quote::format_ident;

    #[derive(Clone, Copy)]
    struct BusPin {
        port: usize,
        pin: u8,
        af: u8,
    }

    #[derive(Clone, Copy)]
    struct DevPin {
        port: usize,
        pin: u8,
        active_low: u8,
    }

    #[derive(Clone)]
    struct Bus {
        node: usize,
        instance: usize,
        hz: u32,
        timingr: u32,
        scl: BusPin,
        sda: BusPin,
    }

    #[derive(Clone)]
    struct Dev {
        node: usize,
        bus_node: usize,
        bus_instance: usize,
        address: u16,
        enable: Option<DevPin>,
        compatible: String,
    }

    fn decode_stm32_pinmux(pinmux: u32) -> (usize, u8, u8) {
        let port_idx = ((pinmux >> 9) & 0x1f) as usize;
        let line = ((pinmux >> 5) & 0x0f) as u8;
        let mode = (pinmux & 0x1f) as u8;
        (port_idx, line, mode)
    }

    fn decode_pinctrl<'a>(dt: &'a DeviceTree, pinctrl: &[u32]) -> Vec<(&'a str, BusPin)> {
        fn parse_i2c_role(name: &str) -> Option<&'static str> {
            let mut parts = name.split('_');
            let periph = parts.next()?;
            let signal = parts.next()?;
            if !periph.starts_with("i2c") {
                return None;
            }
            match signal {
                "scl" => Some("scl"),
                "sda" => Some("sda"),
                _ => None,
            }
        }

        let mut pins = Vec::new();
        for ph in pinctrl {
            let Some(pin) = dt.resolve_phandle_idx(*ph) else {
                panic!("Invalid phandle in pinctrl: {ph:#x}");
            };
            let pin = &dt.nodes[pin];

            let Some(pin_ctrl) = pin.parent else {
                panic!("Pin node has no pin-controller?");
            };
            let pin_ctrl = &dt.nodes[pin_ctrl];

            let (port, line, mode) = match_compatible!(&pin_ctrl.compatible, {
                "st,stm32-pinctrl" => {
                    let pinmux = match pin.extra.get("pinmux") {
                        Some(PropValue::U32Array(v)) if !v.is_empty() => v[0],
                        Some(PropValue::U32(v)) => *v,
                        _ => panic!("Pin node missing pinmux property"),
                    };

                    let (port_idx, line, mode) = decode_stm32_pinmux(pinmux);
                    let base = pin_ctrl
                        .reg
                        .and_then(|(base, _)| usize::try_from(base).ok())
                        .unwrap_or_else(|| {
                            panic!(
                                "Pin controller node {} is missing a valid reg base",
                                pin_ctrl.name
                            )
                        });
                    let port = base + (port_idx * 0x400);
                    (port, line, mode)
                }
            })
            .unwrap_or_else(|| panic!("Unsupported pin-controller: {:?}", pin_ctrl.compatible));

            let name = pin.name.as_str();
            let role = parse_i2c_role(name).unwrap_or_else(|| {
                panic!("Unable to determine I2C signal role from pin name: {name}");
            });

            pins.push((
                role,
                BusPin {
                    port,
                    pin: line,
                    af: mode,
                },
            ));
        }

        pins
    }

    fn collect_buses(dt: &DeviceTree) -> Vec<Bus> {
        let mut buses = Vec::new();

        for (idx, node) in dt.nodes.iter().enumerate() {
            if !is_enabled(node) {
                continue;
            }
            if node.compatible.iter().all(|c| c != "osiris,stm32l4-i2c") {
                continue;
            }

            let Some((base, _)) = node.reg else {
                continue;
            };
            let Ok(instance) = usize::try_from(base) else {
                continue;
            };

            let (mut scl, mut sda) = (None, None);
            for (key, value) in &node.extra {
                if !key.starts_with("pinctrl-") {
                    continue;
                }

                let PropValue::U32Array(pinctrl) = value else {
                    continue;
                };

                for (name, pin) in decode_pinctrl(dt, pinctrl) {
                    let dst = match name {
                        "scl" => &mut scl,
                        "sda" => &mut sda,
                        _ => continue,
                    };
                    *dst = Some(pin);
                }
            }

            buses.push(Bus {
                node: idx,
                instance,
                hz: match node.extra.get("clock-frequency") {
                    Some(PropValue::U32(v)) => *v,
                    _ => 100_000,
                },
                timingr: match node.extra.get("osiris,timingr") {
                    Some(PropValue::U32(v)) => *v,
                    _ => panic!("I2C bus node {} missing osiris,timingr property", node.name),
                },
                scl: scl.expect("I2C pinctrl should define scl"),
                sda: sda.expect("I2C pinctrl should define sda"),
            });
        }

        buses
    }

    fn collect_devices(dt: &DeviceTree, buses: &[Bus]) -> Vec<Dev> {
        let mut devices = Vec::new();

        for bus in buses {
            let bus_node = &dt.nodes[bus.node];
            for child_idx in &bus_node.children {
                let child = &dt.nodes[*child_idx];
                if !is_enabled(child) || child.compatible.is_empty() {
                    continue;
                }

                let address = child
                    .reg
                    .and_then(|(v, _)| u16::try_from(v).ok())
                    .unwrap_or_else(|| {
                        panic!(
                            "I2C device node {} has no valid reg property for address",
                            child.name
                        )
                    });

                let enable = match child.extra.get("enable-gpios") {
                    Some(PropValue::U32Array(v)) if v.len() >= 3 => v.as_slice(),
                    _ => &[],
                };
                let enable = super::decode_gpio_pins(dt, enable);
                if enable.len() > 1 {
                    panic!(
                        "Multiple enable GPIOs specified for I2C device node {}, but only one is supported",
                        child.name
                    );
                }
                let enable = enable.first().map(|(node, pin, active_low)| {
                    let port = node
                        .reg
                        .and_then(|(base, _)| usize::try_from(base).ok())
                        .unwrap_or_else(|| {
                            panic!(
                                "Invalid GPIO controller phandle for enable pin in I2C device node {}",
                                child.name
                            );
                        });
                    DevPin {
                        port,
                        pin: *pin,
                        active_low: *active_low,
                    }
                });

                devices.push(Dev {
                    node: *child_idx,
                    bus_node: bus.node,
                    bus_instance: bus.instance,
                    address,
                    enable,
                    compatible: child.compatible[0].clone(),
                });
            }
        }

        devices
    }

    pub fn emit_registry(dt: &DeviceTree) -> TokenStream {
        let buses = collect_buses(dt);
        let devices = collect_devices(dt, &buses);

        let dev_entry_tokens = |d: &Dev| {
            let node = d.node;
            let bus_node = d.bus_node;
            let bus_instance = d.bus_instance;
            let address = d.address;
            let compatible = d.compatible.as_str();
            let enable = if let Some(en) = d.enable {
                let en_port = en.port;
                let en_line = en.pin;
                let en_active_low = en.active_low;
                quote! {
                    &[I2cDevPin {
                        port: #en_port,
                        line: #en_line,
                        active_low: #en_active_low,
                    }]
                }
            } else {
                quote! { &[] }
            };

            quote! {
                I2cDeviceRegistryEntry {
                    node: #node,
                    bus_node: #bus_node,
                    bus_instance: #bus_instance,
                    address: #address,
                    enable: #enable,
                    compatible: #compatible,
                },
            }
        };

        let bus_device_arrays = buses.iter().map(|b| {
            let bus_node = b.node;
            let bus_devices_ident = format_ident!("I2C_BUS_{}_DEVICES", bus_node);
            let bus_dev_entries = devices
                .iter()
                .filter(|d| d.bus_node == bus_node)
                .map(dev_entry_tokens);

            quote! {
                const #bus_devices_ident: &[I2cDeviceRegistryEntry] = &[
                    #(#bus_dev_entries)*
                ];
            }
        });

        let bus_entries = buses.iter().map(|b| {
            let node = b.node;
            let instance = b.instance;
            let hz = b.hz;
            let timingr = b.timingr;
            let bus_devices_ident = format_ident!("I2C_BUS_{}_DEVICES", node);

            let scl_port = b.scl.port;
            let scl_line = b.scl.pin;
            let scl_af = b.scl.af;
            let scl = quote! {
                I2cBusPin {
                    port: #scl_port,
                    line: #scl_line,
                    af: #scl_af,
                }
            };

            let sda_port = b.sda.port;
            let sda_line = b.sda.pin;
            let sda_af = b.sda.af;
            let sda = quote! {
                I2cBusPin {
                    port: #sda_port,
                    line: #sda_line,
                    af: #sda_af,
                }
            };

            quote! {
                I2cBusRegistryEntry {
                    node: #node,
                    instance: #instance,
                    hz: #hz,
                    timingr: #timingr,
                    scl: #scl,
                    sda: #sda,
                    devices: #bus_devices_ident,
                },
            }
        });

        quote! {
            #[derive(Debug, Clone, Copy)]
            #[repr(C)]
            pub struct I2cBusPin {
                pub port: usize,
                pub line: u8,
                pub af: u8,
            }

            #[derive(Debug, Clone, Copy)]
            #[repr(C)]
            pub struct I2cDevPin {
                pub port: usize,
                pub line: u8,
                pub active_low: u8,
            }

            #[derive(Debug, Clone, Copy)]
            #[repr(C)]
            pub struct I2cDeviceRegistryEntry {
                pub node: usize,
                pub bus_node: usize,
                pub bus_instance: usize,
                pub address: u16,
                pub enable: &'static [I2cDevPin],
                pub compatible: &'static str,
            }

            #[derive(Debug, Clone, Copy)]
            #[repr(C)]
            pub struct I2cBusRegistryEntry {
                pub node: usize,
                pub instance: usize,
                pub hz: u32,
                pub timingr: u32,
                pub scl: I2cBusPin,
                pub sda: I2cBusPin,
                pub devices: &'static [I2cDeviceRegistryEntry],
            }

            #(#bus_device_arrays)*

            pub const I2C_BUS_REGISTRY: &[I2cBusRegistryEntry] = &[
                #(#bus_entries)*
            ];
        }
    }

    pub fn emit_query_api() -> TokenStream {
        quote! {
            pub fn i2c_bus_by_dev(dev: &I2cDeviceRegistryEntry) -> Option<&'static I2cBusRegistryEntry> {
                I2C_BUS_REGISTRY.iter().find(|b| b.node == dev.bus_node)
            }

            pub fn i2c_device_by_compatible(compatible: &str, ord: usize) -> Option<&'static I2cDeviceRegistryEntry> {
                let mut matches = 0usize;
                for bus in I2C_BUS_REGISTRY {
                    for dev in bus.devices {
                        if dev.compatible == compatible {
                            if matches == ord {
                                return Some(dev);
                            }
                            matches += 1;
                        }
                    }
                }
                None
            }
        }
    }
}

// ------------------------------------------------------------------------------------------------
// SPI registry
// ------------------------------------------------------------------------------------------------

mod spi {
    use super::*;
    use quote::format_ident;

    #[derive(Clone, Copy)]
    struct BusPin {
        port: usize,
        pin: u8,
        af: u8,
    }

    #[derive(Clone, Copy)]
    struct DevPin {
        port: usize,
        pin: u8,
        active_low: u8,
    }

    #[derive(Clone)]
    struct Bus {
        node: usize,
        instance: usize,
        sck: BusPin,
        miso: BusPin,
        mosi: BusPin,
    }

    #[derive(Clone)]
    struct Dev {
        node: usize,
        bus_node: usize,
        bus_instance: usize,
        cs: DevPin,
        enable: Option<DevPin>,
        max_hz: u32,
        cpol: u8,
        cpha: u8,
        bits_per_word: u8,
        cs_setup_delay_us: u32,
        cs_hold_delay_us: u32,
        cs_inactive_delay_us: u32,
        compatible: String,
    }

    /// Decodes the STM32_PINMUX macro encoding.
    fn decode_stm32_pinmux(pinmux: u32) -> (usize, u8, u8) {
        let port_idx = ((pinmux >> 9) & 0x1f) as usize;
        let line = ((pinmux >> 5) & 0x0f) as u8;
        let mode = (pinmux & 0x1f) as u8;
        (port_idx, line, mode)
    }

    /// Decodes pinctrl phandles to extract port, line, and alternate function for SPI pins.
    fn decode_pinctrl<'a>(dt: &'a DeviceTree, pinctrl: &[u32]) -> Vec<(&'a str, BusPin)> {
        /// Parses a node name like "spi1-sck" to extract the SPI signal role (sck, miso, mosi).
        fn parse_spi_role(name: &str) -> Option<&'static str> {
            let mut parts = name.split('_');
            let periph = parts.next()?;
            let signal = parts.next()?;
            if !periph.starts_with("spi") {
                return None;
            }
            match signal {
                "sck" => Some("sck"),
                "miso" => Some("miso"),
                "mosi" => Some("mosi"),
                _ => None,
            }
        }

        let mut pins = Vec::new();
        for ph in pinctrl {
            let Some(pin) = dt.resolve_phandle_idx(*ph) else {
                panic!("Invalid phandle in pinctrl: {ph:#x}");
            };
            let pin = &dt.nodes[pin];

            let Some(pin_ctrl) = pin.parent else {
                panic!("Pin node has no pin-controller?");
            };
            let pin_ctrl = &dt.nodes[pin_ctrl];

            let (port, line, mode) = match_compatible!(&pin_ctrl.compatible, {
                // New pinctrl decoders go here.
                "st,stm32-pinctrl" => {
                    let pinmux = match pin.extra.get("pinmux") {
                        Some(PropValue::U32Array(v)) if !v.is_empty() => v[0],
                        Some(PropValue::U32(v)) => *v,
                        _ => panic!("Pin node missing pinmux property"),
                    };

                    let (port_idx, line, mode) = decode_stm32_pinmux(pinmux);
                    let base = pin_ctrl
                        .reg
                        .and_then(|(base, _)| usize::try_from(base).ok())
                        .unwrap_or_else(|| {
                            panic!(
                                "Pin controller node {} is missing a valid reg base",
                                pin_ctrl.name
                            )
                        });
                    let port = base + (port_idx * 0x400);
                    (port, line, mode)
                }
            })
            .unwrap_or_else(|| panic!("Unsupported pin-controller: {:?}", pin_ctrl.compatible));
            let name = pin.name.as_str();

            let role = match parse_spi_role(name) {
                Some(r) => r,
                None => {
                    println!("Unable to determine SPI signal role from pin name: {name}");
                    continue;
                }
            };

            pins.push((
                role,
                BusPin {
                    port,
                    pin: line,
                    af: mode,
                },
            ));
        }

        pins
    }

    fn decode_dev_pins(dt: &DeviceTree, gpios: &[u32]) -> Vec<DevPin> {
        let pins = decode_gpio_pins(dt, gpios);
        pins.into_iter()
            .map(|(node, pin, active_low)| {
                let port = node
                    .reg
                    .and_then(|(base, _)| usize::try_from(base).ok())
                    .unwrap_or_else(|| {
                        panic!("Invalid GPIO controller phandle for CS: {}", node.name);
                    });
                DevPin {
                    port,
                    pin,
                    active_low,
                }
            })
            .collect()
    }

    fn collect_buses(dt: &DeviceTree) -> Vec<Bus> {
        let mut buses: Vec<Bus> = Vec::new();

        // Look for spi controllers
        for (idx, node) in dt.nodes.iter().enumerate() {
            if !is_enabled(node) {
                continue;
            }
            if node.compatible.iter().all(|c| c != "osiris,stm32l4-spi") {
                continue;
            }

            let Some((base, _)) = node.reg else {
                continue;
            };

            let Ok(instance) = usize::try_from(base) else {
                continue;
            };

            let (mut sck, mut miso, mut mosi) = (None, None, None);

            for (key, value) in &node.extra {
                if !key.starts_with("pinctrl-") {
                    continue;
                }

                let PropValue::U32Array(pinctrl) = value else {
                    continue;
                };

                for (name, pin) in decode_pinctrl(dt, pinctrl) {
                    let dst = match name {
                        "sck" => &mut sck,
                        "miso" => &mut miso,
                        "mosi" => &mut mosi,
                        _ => continue,
                    };

                    *dst = Some(pin);
                }
            }

            let sck = sck.expect("SPI pinctrl should define sck");
            let miso = miso.expect("SPI pinctrl should define miso");
            let mosi = mosi.expect("SPI pinctrl should define mosi");

            let bus = Bus {
                node: idx,
                instance,
                sck,
                miso,
                mosi,
            };
            buses.push(bus);
        }
        buses
    }

    fn collect_devices(dt: &DeviceTree, buses: &[Bus]) -> Vec<Dev> {
        let mut devices: Vec<Dev> = Vec::new();

        for bus in buses {
            let bus_node = &dt.nodes[bus.node];
            let cs = match bus_node.extra.get("cs-gpios") {
                Some(PropValue::U32Array(v)) => v,
                _ => panic!("SPI bus node {} missing cs-gpios property", bus_node.name),
            };
            let cs = decode_dev_pins(dt, cs);

            // The peripherals connected to the bus
            for child_idx in &bus_node.children {
                let child = &dt.nodes[*child_idx];
                if !is_enabled(child) || child.compatible.is_empty() {
                    continue;
                }

                let cs_idx = child
                    .reg
                    .and_then(|(v, _)| usize::try_from(v).ok())
                    .unwrap_or_else(|| {
                        panic!(
                            "SPI device node {} has no reg property to specify CS index",
                            child.name
                        );
                    });

                let cs = cs[cs_idx];

                let max_hz = match child.extra.get("spi-max-frequency") {
                    Some(PropValue::U32(v)) => *v,
                    _ => panic!(
                        "SPI device node {} missing spi-max-frequency property",
                        child.name
                    ),
                };

                let enable = match child.extra.get("enable-gpios") {
                    Some(PropValue::U32Array(v)) if v.len() >= 3 => v.as_slice(),
                    _ => &[], // Optional - device may have no enable GPIOs
                };
                // TODO: Only one enable pin for now.
                let enable = decode_dev_pins(dt, enable);
                if enable.len() > 1 {
                    panic!(
                        "Multiple enable GPIOs specified for SPI device node {}, but only one is supported",
                        child.name
                    );
                }
                let enable = enable.first().cloned();

                let cpol = if child.extra.contains_key("spi-cpol") {
                    1
                } else {
                    0
                };

                let cpha = if child.extra.contains_key("spi-cpha") {
                    1
                } else {
                    0
                };

                let bits_per_word = match child.extra.get("spi-word-size") {
                    Some(PropValue::U32(v)) => u8::try_from(*v).unwrap_or_else(|_| {
                        panic!(
                            "SPI device node {} has spi-word-size out of u8 range: {}",
                            child.name, v
                        )
                    }),
                    _ => 8,
                };

                let cs_setup_delay_us = match child.extra.get("spi-cs-setup-delay-us") {
                    Some(PropValue::U32(v)) => *v,
                    _ => 0,
                };
                let cs_hold_delay_us = match child.extra.get("spi-cs-hold-delay-us") {
                    Some(PropValue::U32(v)) => *v,
                    _ => 0,
                };
                let cs_inactive_delay_us = match child.extra.get("spi-cs-inactive-delay-us") {
                    Some(PropValue::U32(v)) => *v,
                    _ => match child.extra.get("spi-post-delay-us") {
                        Some(PropValue::U32(v)) => *v,
                        _ => 0,
                    },
                };
                devices.push(Dev {
                    node: *child_idx,
                    bus_node: bus.node,
                    bus_instance: bus.instance,
                    cs,
                    enable,
                    max_hz,
                    cpol,
                    cpha,
                    bits_per_word,
                    cs_setup_delay_us,
                    cs_hold_delay_us,
                    cs_inactive_delay_us,
                    compatible: child.compatible[0].clone(),
                });
            }
        }

        devices
    }

    pub fn emit_registry(dt: &DeviceTree) -> TokenStream {
        let buses = collect_buses(dt);
        let devices = collect_devices(dt, &buses);

        let dev_entry_tokens = |d: &Dev| {
            let node = d.node;
            let bus_node = d.bus_node;
            let bus_instance = d.bus_instance;

            let cs_port = d.cs.port;
            let cs_line = d.cs.pin;
            let cs_active_low = d.cs.active_low;
            let cs = quote! {
                SpiDevPin {
                    port: #cs_port,
                    line: #cs_line,
                    active_low: #cs_active_low,
                }
            };

            let enable = if let Some(en) = d.enable {
                let en_port = en.port;
                let en_line = en.pin;
                let en_active_low = en.active_low;
                quote! {
                    &[SpiDevPin {
                        port: #en_port,
                        line: #en_line,
                        active_low: #en_active_low,
                    }]
                }
            } else {
                quote! { &[] }
            };

            let max_hz = d.max_hz;
            let cpol = d.cpol;
            let cpha = d.cpha;
            let bits_per_word = d.bits_per_word;
            let cs_setup_delay_us = d.cs_setup_delay_us;
            let cs_hold_delay_us = d.cs_hold_delay_us;
            let cs_inactive_delay_us = d.cs_inactive_delay_us;
            let compatible = d.compatible.as_str();

            quote! {
                SpiDeviceRegistryEntry {
                    node: #node,
                    bus_node: #bus_node,
                    bus_instance: #bus_instance,
                    cs: #cs,
                    enable: #enable,
                    max_hz: #max_hz,
                    cpol: #cpol,
                    cpha: #cpha,
                    bits_per_word: #bits_per_word,
                    cs_setup_delay_us: #cs_setup_delay_us,
                    cs_hold_delay_us: #cs_hold_delay_us,
                    cs_inactive_delay_us: #cs_inactive_delay_us,
                    compatible: #compatible,
                },
            }
        };

        let bus_device_arrays = buses.iter().map(|b| {
            let bus_node = b.node;
            let bus_devices_ident = format_ident!("SPI_BUS_{}_DEVICES", bus_node);
            let bus_dev_entries = devices
                .iter()
                .filter(|d| d.bus_node == bus_node)
                .map(dev_entry_tokens);

            quote! {
                const #bus_devices_ident: &[SpiDeviceRegistryEntry] = &[
                    #(#bus_dev_entries)*
                ];
            }
        });

        let bus_entries = buses.iter().map(|b| {
            let node = b.node;
            let instance = b.instance;
            let bus_devices_ident = format_ident!("SPI_BUS_{}_DEVICES", node);

            let sck_port = b.sck.port;
            let sck_line = b.sck.pin;
            let sck_af = b.sck.af;
            let sck = quote! {
                SpiBusPin {
                    port: #sck_port,
                    line: #sck_line,
                    af: #sck_af,
                }
            };

            let miso_port = b.miso.port;
            let miso_line = b.miso.pin;
            let miso_af = b.miso.af;
            let miso = quote! {
                SpiBusPin {
                    port: #miso_port,
                    line: #miso_line,
                    af: #miso_af,
                }
            };

            let mosi_port = b.mosi.port;
            let mosi_line = b.mosi.pin;
            let mosi_af = b.mosi.af;
            let mosi = quote! {
                SpiBusPin {
                    port: #mosi_port,
                    line: #mosi_line,
                    af: #mosi_af,
                }
            };

            quote! {
                SpiBusRegistryEntry {
                    node: #node,
                    instance: #instance,
                    sck: #sck,
                    miso: #miso,
                    mosi: #mosi,
                    devices: #bus_devices_ident,
                },
            }
        });

        quote! {
            #[derive(Debug, Clone, Copy)]
            #[repr(C)]
            pub struct SpiBusPin {
                pub port: usize,
                pub line: u8,
                pub af: u8,
            }

            #[derive(Debug, Clone, Copy)]
            #[repr(C)]
            pub struct SpiDevPin {
                pub port: usize,
                pub line: u8,
                pub active_low: u8,
            }

            #[derive(Debug, Clone, Copy)]
            #[repr(C)]
            pub struct SpiDeviceRegistryEntry {
                pub node: usize,
                pub bus_node: usize,
                pub bus_instance: usize,
                pub cs: SpiDevPin,
                pub enable: &'static [SpiDevPin],
                pub max_hz: u32,
                pub cpol: u8,
                pub cpha: u8,
                pub bits_per_word: u8,
                pub cs_setup_delay_us: u32,
                pub cs_hold_delay_us: u32,
                pub cs_inactive_delay_us: u32,
                pub compatible: &'static str,
            }

            #[derive(Debug, Clone, Copy)]
            #[repr(C)]
            pub struct SpiBusRegistryEntry {
                pub node: usize,
                pub instance: usize,
                pub sck: SpiBusPin,
                pub miso: SpiBusPin,
                pub mosi: SpiBusPin,
                pub devices: &'static [SpiDeviceRegistryEntry],
            }

            #(#bus_device_arrays)*

            pub const SPI_BUS_REGISTRY: &[SpiBusRegistryEntry] = &[
                #(#bus_entries)*
            ];
        }
    }

    pub fn emit_query_api() -> TokenStream {
        quote! {
            pub fn spi_bus_by_dev(dev: &SpiDeviceRegistryEntry) -> Option<&'static SpiBusRegistryEntry> {
                SPI_BUS_REGISTRY.iter().find(|b| b.node == dev.bus_node)
            }

            pub fn spi_device_by_compatible(compatible: &str, ord: usize) -> Option<&'static SpiDeviceRegistryEntry> {
                let mut matches = 0usize;
                for bus in SPI_BUS_REGISTRY {
                    for dev in bus.devices {
                        if dev.compatible == compatible {
                            if matches == ord {
                                return Some(dev);
                            }
                            matches += 1;
                        }
                    }
                }
                None
            }
        }
    }
}

fn resolve_path(dt: &DeviceTree, path: &str) -> Option<usize> {
    if path == "/" {
        return Some(dt.root);
    }

    let mut current_idx = dt.root;

    // split "/soc/serial@40013800" into ["soc", "serial@40013800"]
    let segments = path.split('/').filter(|s| !s.is_empty());
    for segment in segments {
        let current_node = &dt.nodes[current_idx];

        // look through children of the current node for a matching name
        let found_child = current_node
            .children
            .iter()
            .find(|&&child_idx| dt.nodes[child_idx].name == segment);

        if let Some(&next_idx) = found_child {
            current_idx = next_idx;
        } else {
            return None; // Path broken
        }
    }
    Some(current_idx)
}

// ------------------------------------------------------------------------------------------------
// Alias module
// ------------------------------------------------------------------------------------------------

fn emit_aliases_module(dt: &DeviceTree) -> TokenStream {
    let pairs: Vec<(String, usize)> = dt
        .by_name
        .get("aliases")
        .and_then(|indices| indices.first())
        .map(|&idx| {
            dt.nodes[idx]
                .extra
                .iter()
                .filter_map(|(k, val)| {
                    if let crate::ir::PropValue::Str(path) = val {
                        resolve_path(dt, path).map(|target_idx| (k.clone(), target_idx))
                    } else {
                        None
                    }
                })
                .collect()
        })
        .unwrap_or_default();

    let mut pairs = pairs;
    pairs.sort_by(|a, b| a.0.cmp(&b.0));

    let entries = pairs.iter().map(|(name, idx)| {
        quote! { (#name, #idx), }
    });

    quote! {
        pub mod aliases {
            use super::{Peripheral, peripheral_by_node};

            pub const ALIASES: &[(&str, usize)] = &[
                #(#entries)*
            ];

            #[doc = "resolve an alias name to its Peripheral"]
            pub fn resolve(alias: &str) -> Option<&'static Peripheral> {
                ALIASES
                    .iter()
                    .find(|(k, _)| *k == alias)
                    .and_then(|(_, idx)| peripheral_by_node(*idx))
            }
        }
    }
}

// ------------------------------------------------------------------------------------------------
// Memory module
// ------------------------------------------------------------------------------------------------

fn emit_memory_module(dt: &DeviceTree) -> TokenStream {
    let mut regions: Vec<(&str, u64, u64)> = dt
        .nodes
        .iter()
        .filter(|n| n.name.starts_with("memory@") || n.name == "memory")
        .filter_map(|n| {
            let (base, size) = n.reg?;
            Some((n.name.as_str(), base, size))
        })
        .collect();
    regions.sort_by_key(|&(_, base, _)| base);

    let entries = regions.iter().map(|(name, base, size)| {
        let base = *base as usize;
        let size = *size as usize;

        quote! { (#name, #base, #size), }
    });

    quote! {
        pub mod memory {
            #[doc = "physical memory regions"]
            pub const REGIONS: &[(&str, usize, usize)] = &[
                #(#entries)*
            ];

            #[doc = "find a memory region by node name"]
            pub fn region_by_name(name: &str) -> Option<(usize, usize)> {
                REGIONS
                    .iter()
                    .find(|(n, _, _)| *n == name)
                    .map(|(_, base, size)| (*base, *size))
            }

            #[doc = "total memory in bytes across all declared regions"]
            pub fn total_bytes() -> usize {
                REGIONS.iter().map(|(_, _, size)| size).sum()
            }
        }
    }
}

fn emit_chosen_module(dt: &DeviceTree) -> TokenStream {
    let chosen = dt
        .by_name
        .get("chosen")
        .and_then(|indices| indices.first())
        .map(|&idx| &dt.nodes[idx]);

    let mut periph_indices: Vec<usize> = Vec::new();
    dt.walk(|idx, node| {
        if !node.compatible.is_empty() {
            periph_indices.push(idx);
        }
    });

    let stdout_periph_idx: Option<usize> = chosen.and_then(|n| {
        if let Some(crate::ir::PropValue::Str(raw)) = n.extra.get("stdout-path") {
            let path = raw.split(':').next().unwrap_or(raw);
            let node_idx = if path.contains('/') {
                resolve_path(dt, path)
            } else {
                dt.by_name
                    .get("aliases")
                    .and_then(|ids| ids.first())
                    .and_then(|&aidx| {
                        if let Some(crate::ir::PropValue::Str(resolved)) =
                            dt.nodes[aidx].extra.get(path)
                        {
                            resolve_path(dt, resolved)
                        } else {
                            None
                        }
                    })
            }?;
            periph_indices.iter().position(|&idx| idx == node_idx)
        } else {
            None
        }
    });

    let bootargs: Option<&str> = chosen.and_then(|n| {
        if let Some(crate::ir::PropValue::Str(s)) = n.extra.get("bootargs") {
            Some(s.as_str())
        } else {
            None
        }
    });

    const KNOWN: &[&str] = &["stdout-path", "bootargs"];
    let extras: Vec<(&str, &crate::ir::PropValue)> = chosen
        .map(|n| {
            let mut v: Vec<_> = n
                .extra
                .iter()
                .filter(|(k, _)| !KNOWN.contains(&k.as_str()))
                .map(|(k, v)| (k.as_str(), v))
                .collect();
            v.sort_by_key(|(k, _)| *k);
            v
        })
        .unwrap_or_default();

    // backing statics for array types that can't be expressed inline
    let backing_statics = extras
        .iter()
        .enumerate()
        .filter_map(|(i, (_, val))| match val {
            crate::ir::PropValue::U32Array(arr) => {
                let ident = quote::format_ident!("CHOSEN_EXTRA_{}", i);
                Some(quote! {
                    static #ident: &[u32] = &[#(#arr),*];
                })
            }
            crate::ir::PropValue::Bytes(arr) => {
                let ident = quote::format_ident!("CHOSEN_EXTRA_{}", i);
                Some(quote! {
                    static #ident: &[u8] = &[#(#arr),*];
                })
            }
            _ => None,
        });

    let stdout_tokens = match stdout_periph_idx {
        Some(idx) => quote! {
            #[doc = "index into PERIPHERALS of the stdout peripheral, resolved from stdout-path"]
            pub const STDOUT: Option<usize> = Some(#idx);
        },
        None => quote! {
            pub const STDOUT: Option<usize> = None;
        },
    };

    let bootargs_tokens = match bootargs {
        Some(s) => quote! {
            pub const BOOTARGS: Option<&str> = Some(#s);
        },
        None => quote! {
            pub const BOOTARGS: Option<&str> = None;
        },
    };

    let extra_entries = extras.iter().enumerate().map(|(i, (key, val))| {
        let val_tokens = match val {
            crate::ir::PropValue::Empty => quote! { PropValue::Empty },
            crate::ir::PropValue::U32(v) => {
                let lit = syn::LitInt::new(&format!("{v:#010x}"), proc_macro2::Span::call_site());
                quote! { PropValue::U32(#lit) }
            }
            crate::ir::PropValue::U32Array(_) => {
                let ident = quote::format_ident!("CHOSEN_EXTRA_{}", i);
                quote! { PropValue::U32Array(#ident.to_vec()) }
            }
            crate::ir::PropValue::Str(s) => quote! { PropValue::Str(#s) },
            crate::ir::PropValue::StringList(sl) => {
                quote! { PropValue::StringList(vec![#(#sl),*]) }
            }
            crate::ir::PropValue::Bytes(_) => {
                let ident = quote::format_ident!("CHOSEN_EXTRA_{}", i);
                quote! { PropValue::Bytes(#ident.to_vec()) }
            }
        };
        quote! { (#key, #val_tokens), }
    });

    quote! {
        #(#backing_statics)*

        pub mod chosen {
            use super::{PERIPHERALS, Peripheral, PropValue};

            #stdout_tokens
            #bootargs_tokens

            #[doc = "non-standard properties of the chosen node"]
            pub const EXTRAS: &[(&str, PropValue)] = &[
                #(#extra_entries)*
            ];

            #[doc = "resolve stdout to its Peripheral directly via PERIPHERALS index"]
            pub fn stdout() -> Option<&'static Peripheral> {
                STDOUT.map(|idx| &PERIPHERALS[idx])
            }
        }
    }
}
