use crate::ir::{DeviceTree, PropValue};

pub fn generate_rust(dt: &DeviceTree) -> String {
    let mut out = String::new();
    emit_header(&mut out);
    emit_prop_value_type(&mut out);
    emit_topology_type(&mut out);
    emit_peripheral_type(&mut out);
    emit_nodes(&mut out, dt);
    emit_peripherals(&mut out, dt);
    emit_board_identity(&mut out, dt);
    emit_query_api(&mut out, dt);
    out
}

// ================================================================================================
// File header
// ================================================================================================

fn emit_header(out: &mut String) {
    out.push_str(
        r#"// ================================
// GENERATED BY dtgen — DO NOT EDIT
// ================================

#![allow(dead_code)]

"#,
    );
}

// ================================================================================================
// Type defitions
// ================================================================================================

fn emit_prop_value_type(out: &mut String) {
    out.push_str(
        r#"#[derive(Debug, Clone, Copy, PartialEq)]
pub enum PropValue {
    Empty,
    U32(u32),
    U32Array(&'static [u32]),
    Str(&'static str),
    StringList(&'static [&'static str]),
    Bytes(&'static [u8]),
}

"#,
    );
}

fn emit_topology_type(out: &mut String) {
    out.push_str(
        r#"#[derive(Debug, Clone, Copy)]
pub struct TreeNode {
    pub name:     &'static str,
    pub phandle:  Option<u32>,
    pub parent:   Option<usize>,
    pub children: &'static [usize],
}

impl TreeNode {
    /// Returns the parent TreeNode, if any.
    pub fn parent_node(&self) -> Option<&'static TreeNode> {
        self.parent.map(|idx| &NODES[idx])
    }

    /// Iterate children as (node_index, &TreeNode).
    pub fn iter_children(&self) -> impl Iterator<Item = (usize, &'static TreeNode)> {
        self.children.iter().map(|&idx| (idx, &NODES[idx]))
    }
}

"#,
    );
}

fn emit_peripheral_type(out: &mut String) {
    out.push_str(
        r#"#[derive(Debug, Clone, Copy)]
pub struct Peripheral {
    pub node:       usize,
    pub compatible: &'static [&'static str],
    pub reg:        Option<(usize, usize)>,
    pub interrupts: &'static [u32],
    pub phandle:    Option<u32>,
    pub props:      &'static [(&'static str, PropValue)],
}

impl Peripheral {
    /// Returns true if any compatible string exactly matches `c`.
    pub fn is_compatible(&self, c: &str) -> bool {
        self.compatible.iter().any(|&s| s == c)
    }

    /// Returns true if any compatible string contains `fragment` as a substring.
    pub fn compatible_contains(&self, fragment: &str) -> bool {
        self.compatible.iter().any(|&s| s.contains(fragment))
    }

    /// Look up a prop by key, returning the raw PropValue.
    pub fn prop(&self, key: &str) -> Option<PropValue> {
        self.props.iter().find(|(k, _)| *k == key).map(|(_, v)| *v)
    }

    /// Convenience: get a u32 prop.
    pub fn prop_u32(&self, key: &str) -> Option<u32> {
        match self.prop(key) {
            Some(PropValue::U32(v)) => Some(v),
            _ => None,
        }
    }

    /// Convenience: get a str prop.
    pub fn prop_str(&self, key: &str) -> Option<&'static str> {
        match self.prop(key) {
            Some(PropValue::Str(s)) => Some(s),
            _ => None,
        }
    }

    /// Convenience: get a u32 array prop.
    pub fn prop_u32_array(&self, key: &str) -> Option<&'static [u32]> {
        match self.prop(key) {
            Some(PropValue::U32Array(arr)) => Some(arr),
            _ => None,
        }
    }

    /// Returns the base address from reg, if present.
    pub fn reg_base(&self) -> Option<usize> {
        self.reg.map(|(base, _)| base)
    }

    /// Returns the size from reg, if present.
    pub fn reg_size(&self) -> Option<usize> {
        self.reg.map(|(_, size)| size)
    }

    /// Resolve a phandle value (e.g. from a clocks prop) to another Peripheral.
    pub fn resolve_phandle(&self, ph: u32) -> Option<&'static Peripheral> {
        peripheral_by_phandle(ph)
    }

    /// Returns the TreeNode for this peripheral.
    pub fn tree_node(&self) -> &'static TreeNode {
        &NODES[self.node]
    }

    /// Returns true if status prop is absent or set to "okay".
    pub fn is_enabled(&self) -> bool {
        match self.prop_str("status") {
            Some(s) => s == "okay",
            None => true,
        }
    }
}

"#,
    );
}

// ================================================================================================
// Nodes
// ================================================================================================

fn emit_nodes(out: &mut String, dt: &DeviceTree) {
    out.push_str("pub const NODES: &[TreeNode] = &[\n");
    for (i, node) in dt.nodes.iter().enumerate() {
        let phandle = opt_u32(node.phandle);
        let parent = opt_usize(node.parent);
        let children = if node.children.is_empty() {
            "&[]".to_string()
        } else {
            let inner: Vec<String> = node.children.iter().map(|c| c.to_string()).collect();
            format!("&[{}]", inner.join(", "))
        };
        out.push_str(&format!(
            "    // {i}\n    TreeNode {{ name: {:?}, phandle: {phandle}, parent: {parent}, children: {children} }},\n",
            node.name,
        ));
    }
    out.push_str("];\n\n");
}

// ================================================================================================
// Peripherals
// ================================================================================================

fn emit_peripherals(out: &mut String, dt: &DeviceTree) {
    let mut indices: Vec<usize> = Vec::new();
    dt.walk(|idx, node| {
        if !node.compatible.is_empty() {
            indices.push(idx);
        }
    });

    // emit per-node prop sub-consts (only for types that cannot be inlined)
    for (i, &idx) in indices.iter().enumerate() {
        let node = &dt.nodes[idx];

        let mut sorted_extra: Vec<(&String, &PropValue)> = node.extra.iter().collect();
        sorted_extra.sort_by_key(|(k, _)| k.as_str());

        for (j, (_, val)) in sorted_extra.iter().enumerate() {
            match val {
                PropValue::U32Array(arr) => {
                    let vals: Vec<String> = arr.iter().map(|v| v.to_string()).collect();
                    out.push_str(&format!(
                        "const PERIPH_{i}_PROP_{j}: &[u32] = &[{}];\n",
                        vals.join(", ")
                    ));
                }
                PropValue::StringList(list) => {
                    let strs: Vec<String> = list.iter().map(|s| format!("{:?}", s)).collect();
                    out.push_str(&format!(
                        "const PERIPH_{i}_PROP_{j}_STRS: &[&str] = &[{}];\n",
                        strs.join(", ")
                    ));
                }
                PropValue::Bytes(b) => {
                    let bytes: Vec<String> = b.iter().map(|v| format!("{:#04x}", v)).collect();
                    out.push_str(&format!(
                        "const PERIPH_{i}_PROP_{j}_BYTES: &[u8] = &[{}];\n",
                        bytes.join(", ")
                    ));
                }
                _ => {}
            }
        }

        // props array
        let mut prop_entries: Vec<String> = Vec::new();
        for (j, (key, val)) in sorted_extra.iter().enumerate() {
            let pv = match val {
                PropValue::Empty => "PropValue::Empty".to_string(),
                PropValue::U32(v) => format!("PropValue::U32({v})"),
                PropValue::U32Array(_) => format!("PropValue::U32Array(PERIPH_{i}_PROP_{j})"),
                PropValue::Str(s) => format!("PropValue::Str({:?})", s),
                PropValue::StringList(_) => {
                    format!("PropValue::StringList(PERIPH_{i}_PROP_{j}_STRS)")
                }
                PropValue::Bytes(_) => format!("PropValue::Bytes(PERIPH_{i}_PROP_{j}_BYTES)"),
            };
            prop_entries.push(format!("    ({:?}, {})", key, pv));
        }

        out.push_str(&format!(
            "const PERIPH_{i}_PROPS: &[(&str, PropValue)] = &[\n{}\n];\n",
            prop_entries.join(",\n")
        ));
    }

    out.push('\n');
    out.push_str("pub const PERIPHERALS: &[Peripheral] = &[\n");

    for (i, &idx) in indices.iter().enumerate() {
        let node = &dt.nodes[idx];

        let compats: Vec<String> = node.compatible.iter().map(|c| format!("{:?}", c)).collect();
        let compat_inline = format!("&[{}]", compats.join(", "));

        let reg = match node.reg {
            Some((base, size)) => format!("Some(({:#010x}, {:#x}))", base, size),
            None => "None".to_string(),
        };

        let irqs = if node.interrupts.is_empty() {
            "&[]".to_string()
        } else {
            let vals: Vec<String> = node.interrupts.iter().map(|v| v.to_string()).collect();
            format!("&[{}]", vals.join(", "))
        };

        let phandle = opt_u32(node.phandle);

        out.push_str(&format!(
            "    // {i} — node {idx}: {:?}\n    Peripheral {{ node: {idx}, compatible: {compat_inline}, reg: {reg}, interrupts: {irqs}, phandle: {phandle}, props: PERIPH_{i}_PROPS }},\n",
            node.name,
        ));
    }

    out.push_str("];\n\n");
}

// ================================================================================================
// Board identity
// ================================================================================================

fn emit_board_identity(out: &mut String, dt: &DeviceTree) {
    out.push_str(&format!("pub const MODEL: &str = {:?};\n\n", dt.model()));
    let stdout = dt
        .stdout_compat()
        .as_deref()
        .map(|s| format!("Some({s:?})"))
        .unwrap_or_else(|| "None".to_string());
    out.push_str(&format!("pub const STDOUT: Option<&str> = {stdout};\n\n"));
}

// ================================================================================================
// Query API
// ================================================================================================

fn emit_query_api(out: &mut String, dt: &DeviceTree) {
    out.push_str(
        r#"/// Find the first enabled peripheral whose compatible list exactly matches `c`.
pub fn peripheral_by_compatible(c: &str) -> Option<&'static Peripheral> {
    PERIPHERALS.iter().find(|p| p.is_compatible(c) && p.is_enabled())
}

/// Iterate all enabled peripherals whose compatible list exactly matches `c`.
pub fn peripherals_by_compatible(c: &str) -> impl Iterator<Item = &'static Peripheral> {
    PERIPHERALS.iter().filter(move |p| p.is_compatible(c) && p.is_enabled())
}

/// Find a peripheral by its phandle value.
/// Ignores enabled status — phandle targets like clock providers may have no status prop.
pub fn peripheral_by_phandle(ph: u32) -> Option<&'static Peripheral> {
    PERIPHERALS.iter().find(|p| p.phandle == Some(ph))
}

/// Find a peripheral by its NODES index.
pub fn peripheral_by_node(idx: usize) -> Option<&'static Peripheral> {
    PERIPHERALS.iter().find(|p| p.node == idx)
}

/// Find a peripheral by node name, with or without unit address.
/// e.g. "serial" matches "serial@40013800".
pub fn peripheral_by_name(name: &str) -> Option<&'static Peripheral> {
    PERIPHERALS.iter().find(|p| {
        let n = NODES[p.node].name;
        n == name || n.split('@').next() == Some(name)
    })
}

"#,
    );

    emit_aliases_module(out, dt);
}

fn emit_aliases_module(out: &mut String, dt: &DeviceTree) {
    let pairs: Vec<(String, String)> = dt
        .by_name
        .get("aliases")
        .map(|&idx| {
            let node = &dt.nodes[idx];
            let mut v: Vec<(String, String)> = node
                .extra
                .iter()
                .filter_map(|(k, val)| {
                    if let crate::ir::PropValue::Str(s) = val {
                        let name = s.split('/').last().unwrap_or(s);
                        Some((k.clone(), name.to_string()))
                    } else {
                        None
                    }
                })
                .collect();
            v.sort_by_key(|(k, _)| k.clone());
            v
        })
        .unwrap_or_default();

    out.push_str("\npub mod aliases {\n");
    out.push_str("    use super::*;\n\n");

    // emit ALIASES slice
    let entries: Vec<String> = pairs
        .iter()
        .map(|(k, v)| format!("        ({:?}, {:?})", k, v))
        .collect();
    out.push_str(&format!(
        "    pub const ALIASES: &[(&str, &str)] = &[\n{}\n    ];\n\n",
        entries.join(",\n")
    ));

    // emit resolve function
    out.push_str(
        r#"    /// Resolve an alias name to its Peripheral.
    pub fn resolve(alias: &str) -> Option<&'static Peripheral> {
        ALIASES
            .iter()
            .find(|(k, _)| *k == alias)
            .and_then(|(_, name)| peripheral_by_name(name))
    }
"#,
    );

    out.push_str("}\n");
}

// ─── Formatting helpers ───────────────────────────────────────────────────────

fn opt_u32(v: Option<u32>) -> String {
    match v {
        Some(n) => format!("Some({n})"),
        None => "None".to_string(),
    }
}

fn opt_usize(v: Option<usize>) -> String {
    match v {
        Some(n) => format!("Some({n:#010x})"),
        None => "None".to_string(),
    }
}
