# This is the default configuration for the STM32L4R5ZI MCU.

[env]
# Debugging configuration
OSIRIS_DEBUG_UART = "LPUART1"
OSIRIS_DEBUG_RUNTIMESYMBOLS = "false"

# Tuning parameters
OSIRIS_TUNING_ENABLEFPU = "false"
OSIRIS_STACKPAGES = "1"
OSIRIS_TUNING_DTS = "nucleo_l4r5zi.dts"

[build]
target = "thumbv7em-none-eabi"