[metadata]
parent = "."


[democategory]
name = "Demo Category"
description = "This is a demo category to show how categories work."

[democategory.demosubcategory]
name = "Demo Subcategory"
description = "This is a demo subcategory to show how subcategories work."
depends_on = [{ key = ".democategory.demooption4", value = "value1" }]

[democategory.demosubcategory.demooption]
name = "Demo Option"
description = "This is a demo option in a subcategory."
type = "String"
default = "This is a default value"

[democategory.demosubcategory.demooption2]
name = "Demo Option 2"
description = "This is another demo option in a subcategory."
type = "Boolean"
default = true

[democategory.demosubcategory.demooption3]
name = "Demo Option 3"
description = "This is a third demo option in a subcategory."
# Integer in the range 0-100
type = { type = "Integer", min = 0, max = 100 }
depends_on = [{ key = ".democategory.demooption4", value = "value2" }]

[democategory.demooption4]
name = "Demo Option 4"
description = "This is a demo option in a category."
# String with allowed values
type = { type = "String", allowed_values = ["value1", "value2", "value3"] }
default = "value2"