[env]
DEMOCATEGORY_DEMOOPTION4 = "value1"
DEMOCATEGORY_DEMOSUBCATEGORY_DEMOOPTION2 = false
DEMOCATEGORY_DEMOSUBCATEGORY_SUBCATEGORY_DEMOOPTION = "test"
DEMOCATEGORY_DEMOSUBCATEGORY_DEMOOPTION = "This is a default value"

