[metadata]
parent = ".demo_category.demo_subcategory"


[subcategory]
name = "Demo Subcategory"
description = "This is a demo subcategory to show how subcategories work."
depends_on = [{ key = "demo_category.demo_option4", value = "value1" }]

[subcategory.demo_option]
name = "Demo Option"
description = "This is a demo option in a subcategory."
type = "String"