[env]
OSIRIS_ARM_HAL = "stm32l4xx"
OSIRIS_DEBUG_UART = "LPUART1"
OSIRIS_ARM_STM32L4XX_MCU = "r5zi"
OSIRIS_TUNING_APPMEMSIZE = "8192"
OSIRIS_DEBUG_RUNTIMESYMBOLS = "false"
OSIRIS_TUNING_ENABLEFPU = "false"
OSIRIS_TUNING_APPSTACKSIZE = "2048"

[alias]
xtask = "run --manifest-path xtask/Cargo.toml --release --"

[target.thumbv7em-none-eabi]
rustflags = ["-C", "relocation-model=ropi-rwpi"]
