include = [
    "../config.toml"
]

[alias]
xtask = "--config xtasks/.cargo/config.toml run -p xtask --release --"

[target.'cfg(target_os = "none")']
rustflags = [
    "-C", "link-arg=--entry=main",
    "-C", "link-arg=-Tlink.ld",
]