#pragma once

// RCC

void HAL_RCC_SYSCFG_CLK_ENABLE(void);
void HAL_RCC_PWR_CLK_ENABLE(void);

void HAL_RCC_LPUART1_CLK_ENABLE(void);

void HAL_RCC_GPIOC_CLK_ENABLE(void);
void HAL_RCC_GPIOH_CLK_ENABLE(void);
void HAL_RCC_GPIOB_CLK_ENABLE(void);
void HAL_RCC_GPIOD_CLK_ENABLE(void);
void HAL_RCC_GPIOG_CLK_ENABLE(void);