[package]
name = "hal-select"
version = "0.1.0"
edition = "2024"
links = "hal"

[dependencies]
hal-api  = { path = "../api" }

[target.'cfg(target_arch = "arm")'.dependencies]
hal-arm = { path = "../arm" }

[dev-dependencies]
hal-testing = { path = "../testing" }